server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
aws:
  region: ${AWS_REGION:ap-northeast-2}

logging:
  level:
    root: INFO
    software.amazon.awssdk: INFO
    com.team.async: DEBUG


sqs:
  queue-url: ${SQS_QUEUE_URL:https://sqs.ap-northeast-2.amazonaws.com/031988646316/async-main-queue}
  dlq-url: ${DLQ_QUEUE_URL:https://sqs.ap-northeast-2.amazonaws.com/031988646316/async-main-dlq}

security:
  jwt:
    secret: "X8jK9qL2zN5pW1rT4vY7xB3mC6hF0gD8sA1kE2oU3iR4tV9wQ5yZ6nJ0"
    ttl-seconds: 3600
