server:
  port: 8082

security:
  jwt:
    secret: "X8jK9qL2zN5pW1rT4vY7xB3mC6hF0gD8sA1kE2oU3iR4tV9wQ5yZ6nJ0"
    ttl-seconds: 3600

ddb:
  table-name: AsyncEventTable

logging:
  level:
    org.springframework.security: DEBUG